app/views/layouts/application.html.erb

body内に、container row col-12を設定しました。

Feature html application

---

app/controllers/admin/genres_controller.rb
app/models/genre.rb
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
config/application.rb

* 投稿フォームの作成
* 一覧テーブルの作成
* フラッシュメッセージの実装
* エラーメッセージの実装
* 編集フォームの作成
* フラッシュメッセージの実装
* エラーメッセージの実装
* バリデーションの実装
* configの追記

[Add]ジャンルの実装

---

app/views/layouts/_errors.html.erb
config/locales/ja.yml

* 頻出英語の日本語化
* ジャンル名の日本語化
*部分テンプレートファイルを日本語で書き直した

[Add]エラーメッセージの日本語化

---

config/locales/ja.yml

[Add]エラーメッセージの日本語化(商品)

---

app/views/admin/items/new.html.erb
config/locales/ja.yml

* 選択項目に"選択してください"を追加
*"選択してください"が選択されて、投稿された際のエラーメッセージを日本語化

[Fix]セレクトボックスの不具合を修正

---

app/controllers/public/cart_items_controller.rb
app/controllers/public/items_controller.rb
app/models/cart_item.rb
app/views/public/cart_items/index.html.erb
app/views/public/items/index.html.erb
app/views/public/items/new.html.erb
app/views/public/items/show.html.erb
config/locales/ja.yml
config/routes.rb

* 商品詳細ページから情報を取得
* テーブル作成
* 各種リンク作成
* 個数変更
* エラーメッセージ表示
* エラーメッセージの日本語化
* バリデーションの実装

[Add]カートの実装

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/admin/registrations_controller.rb
app/controllers/admin/sessions_controller.rb
app/models/admin.rb
app/views/admin/sessions/new.html.erb
db/seeds.rb

管理者ログイン・ログアウト機能の実装
envファイルは.gitignoreでGitHubには投稿されないので、管理者用メールアドレス・パスワードを作成してください。
管理者ログイン情報の取得方法
・/environment/nagano_cakeのファイル直下で、下記をターミナルで実行する。
bundle install
touch .env
・envファイルに下記を記述して保存します。メールアドレス、パスワードは参考例です。
SECRET_EMAIL = "magic@team.com"
SECRET_PASSWORD = "teammagic"
・db/seeds.rbを保存します。
rails db:seed
//テストデータの読み込みをリセットするコマンド
bin/rails db:migrate:reset

管理者ログイン・ログアウト機能の実装

---

app/controllers/public/orders_controller.rb
app/models/shipping_address.rb
app/views/public/orders/confirm.html.erb
app/views/public/orders/finish.html.erb
app/views/public/orders/new.html.erb
config/routes.rb

[Add]注文の実装(顧客)

---

app/assets/stylesheets/public/searches.scss
app/controllers/public/items_controller.rb
app/controllers/public/searches_controller.rb
app/helpers/public/searches_helper.rb
app/models/genre.rb
app/views/public/items/show.html.erb
app/views/public/searches/search.html.erb
config/routes.rb
test/controllers/public/searches_controller_test.rb

* searchesコントローラの作成
* ルーティングの指定
* ビューファイルの編集
* モデルにメソッドを定義

[Add]ジャンル検索機能の実装

---

app/assets/stylesheets/admin/searches.scss
app/controllers/admin/searches_controller.rb
app/controllers/public/homes_controller.rb
app/controllers/public/searches_controller.rb
app/helpers/admin/searches_helper.rb
app/models/genre.rb
app/models/item.rb
app/views/admin/searches/_form.html.erb
app/views/admin/searches/search.html.erb
app/views/layouts/_header.html.erb
app/views/public/homes/top.html.erb
app/views/public/items/_genre_search.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb
app/views/public/searches/_form.html.erb
app/views/public/searches/search.html.erb
config/routes.rb
test/controllers/admin/searches_controller_test.rb

[Add]商品検索機能の実装

---

app/controllers/public/cart_items_controller.rb
app/javascript/stylesheets/application.scss
app/views/layouts/application.html.erb
app/views/public/cart_items/index.html.erb

[Layout]カート商品一覧

---

app/views/public/cart_items/index.html.erb
app/views/public/homes/top.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb

各ページのマージンを統一、コンテナ削除。
商品一覧の商品名、値段のマージンを修正。
商品詳細のレイアウト修正、商品説明の文字数によるレイアウト崩壊を修正。

[Layout]顧客側商品

---

app/controllers/admin/order_items_controller.rb
app/controllers/admin/orders_controller.rb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb

１　注文ステータス
　　入金完了→製作ステータス「製作待ち」
２　製作ステータス
　　製作中→注文ステータス「製作中」
　　製作完了→「発送準備中」

[Fix]会員側注文履歴　ステータス反映

---

app/controllers/public/orders_controller.rb
app/models/customer.rb
app/models/shipping_address.rb
app/views/public/customers/confirm.html.erb
app/views/public/customers/edit.html.erb
app/views/public/registrations/new.html.erb
app/views/public/sessions/new.html.erb
config/locales/ja.yml

[add]担当機能の日本語化、＋一部修正

---

app/controllers/admin/confirmations_controller.rb
app/controllers/admin/customers_controller.rb
app/controllers/admin/genres_controller.rb
app/controllers/admin/homes_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/admin/omniauth_callbacks_controller.rb
app/controllers/admin/order_items_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/admin/passwords_controller.rb
app/controllers/admin/registrations_controller.rb
app/controllers/admin/searches_controller.rb
app/controllers/admin/sessions_controller.rb
app/controllers/admin/unlocks_controller.rb
app/views/admin/_header.html.erb
app/views/admin/searches/_form.html.erb
app/views/layouts/admin_application.html.erb
app/views/public/_header.html.erb
app/views/public/searches/_form.html.erb

* admin用のapplication.html.erbファイルを作成
* customer・adminそれぞれのヘッダーファイルを作成&編集
* adminディレクトリ内のコントローラに呼び出し先を記述
* 検索窓のplaceholderを設定

[Fix]管理者側と顧客側のヘッダーの区別

---

app/views/admin/customers/edit.html.erb
config/locales/ja.yml

１　ログイン時の表示
２　ログアウト時の表示
３　会員情報編集のエラー表示

[Fix]管理者側、日本語化

---

app/controllers/admin/sessions_controller.rb
app/controllers/public/customers_controller.rb
app/controllers/public/sessions_controller.rb
app/views/public/cart_items/index.html.erb

１　会員ログイン後
２　会員退会処理後
３　管理者カート内、買い物を続ける後

[Fix]テスト　ルート先修正

---

app/controllers/admin/customers_controller.rb
app/views/admin/customers/_edit.html.erb
app/views/admin/customers/edit.html.erb
app/views/admin/customers/update.js.erb

[Fix]管理者側　会員情報編集時の名前表示

---

app/controllers/public/cart_items_controller.rb
app/controllers/public/orders_controller.rb
app/models/cart_item.rb
app/views/public/cart_items/index.html.erb
app/views/public/orders/confirm.html.erb

* メソッドの定義
* total → total_price

[Clean]合計金額のメソッド化

---

app/controllers/public/shipping_addresses_controller.rb
app/views/public/shipping_addresses/_form.html.erb
app/views/public/shipping_addresses/_index.html.erb
app/views/public/shipping_addresses/create.js.erb
app/views/public/shipping_addresses/destroy.js.erb
app/views/public/shipping_addresses/index.html.erb

[Fix]　会員側の配送先非同期化

---

app/controllers/admin/order_items_controller.rb
app/controllers/admin/orders_controller.rb
app/views/admin/order_items/_manufacture_status.html.erb
app/views/admin/order_items/update.js.erb
app/views/admin/orders/_manufacture_status.html.erb
app/views/admin/orders/_order_item_table.html.erb
app/views/admin/orders/_order_status.html.erb
app/views/admin/orders/show.html.erb
app/views/admin/orders/update.js.erb
app/views/public/shipping_addresses/create.js.erb

* 部分テンプレートの作成
* jsファイルの記述
* 部分テンプレートの作成
* jsファイルの記述

注文・製作ステータスの非同期化

---

app/views/admin/homes/top.html.erb

[Layout]admin_homes

---

app/javascript/stylesheets/searches.scss
app/views/admin/searches/_form.html.erb
app/views/public/searches/_form.html.erb

[Fix]検索窓とアイコンの境界を削除

---

app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb

margin修正
btnサイズ修正
table activeに変更

[Layout]修正

---

app/views/admin/orders/index.html.erb

Fix 管理者側　レイアウト

---

app/javascript/stylesheets/application.scss
app/javascript/stylesheets/footer.scss
app/javascript/stylesheets/homes.scss
app/views/layouts/_footer.html.erb
app/views/layouts/about.html.erb
app/views/public/orders/finish.html.erb

１　フッターの固定
２　aboutページの修正
３　注文画面の修正

[Fix]レイアウト修正

---

app/views/admin/_header.html.erb
app/views/public/_header.html.erb

１　<ul>を囲んでいるdivからクラスを削除
２　div内にもう一つ<ul>を作成してsearchを入れ込みました。

Fix 検索窓の位置変更

---

app/controllers/admin/homes_controller.rb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
config/locales/ja.yml

[Fix]ページネーション編集

---

app/controllers/application_controller.rb
app/javascript/stylesheets/application.scss
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb

１　ジャンル、一覧、編集画面
２　商品一覧、新規登録、編集画面
３　ラジオボタン配色

Fix管理者側レイアウト

---

app/views/admin/customers/index.html.erb

[Update]ページネーションの位置変更

---

app/javascript/stylesheets/application.scss
app/javascript/stylesheets/font.scss
app/views/admin/orders/show.html.erb

* font.scssを削除、application.scssにまとめた
* strongのcssを指定
* 注文履歴詳細にstrongタグを追加

[Update]strongのcssを指定

---

app/controllers/admin/homes_controller.rb
app/controllers/admin/order_items_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/public/customers_controller.rb
app/javascript/stylesheets/application.scss
app/javascript/stylesheets/header.scss
app/views/public/_header.html.erb
app/views/public/customers/_form.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/update.js.erb

１　パブリック側ヘッダーに名前を追加
２　会員情報編集画面の非同期化

[add]ヘッダー会員名

---

app/controllers/admin/confirmations_controller.rb
app/controllers/admin/customers_controller.rb
app/controllers/admin/genres_controller.rb
app/controllers/admin/homes_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/admin/omniauth_callbacks_controller.rb
app/controllers/admin/order_items_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/admin/passwords_controller.rb
app/controllers/admin/registrations_controller.rb
app/controllers/admin/searches_controller.rb
app/controllers/admin/sessions_controller.rb
app/controllers/admin/unlocks_controller.rb
app/controllers/public/cart_items_controller.rb
app/controllers/public/customers_controller.rb
app/controllers/public/homes_controller.rb
app/controllers/public/items_controller.rb
app/controllers/public/orders_controller.rb
app/controllers/public/registrations_controller.rb
app/controllers/public/searches_controller.rb
app/controllers/public/sessions_controller.rb
app/controllers/public/shipping_addresses_controller.rb
app/views/admin/searches/search.html.erb
app/views/public/cart_items/_cart_items.html.erb

Fix コントローラのインデント修正

---

app/javascript/stylesheets/application.scss
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
app/views/admin/items/edit.html.erb
app/views/admin/items/new.html.erb
app/views/public/orders/confirm.html.erb

１　商品新規登録時
２　商品編集時
３　ジャンル新規登録時
４　ジャンル更新時
５　ヘッダーのフォント

[Fix]管理者エラーメッセージ
